PBP Template: Drivers/CTS_NVM_Driver/CTS_NVM_drv.h File Reference
CTS_NVM_drv.h File Reference
CTS_NVM_drv Header.
#include "Global.h"
#include "HardwareConfig.h"
Data Structures
struct cts_nvm_head_t
struct cts_nvm_frame_t
NVM frame structure, allows for convenient hardware implementation.
Macros
#define CTS_NVM_FRAME_BYTES (512)
#define CTS_NVM_MAX_CYCLES (0)
#define CTS_NVM_BASE_ADDRESS (0x080E0000)
#define CTS_NVM_HEADER_BYTES (sizeof(cts_nvm_head_t))
#define CTS_NVM_DATA_BYTES (CTS_NVM_FRAME_BYTES - CTS_NVM_HEADER_BYTES)
Typedefs
typedef enum cts_nvm_ret_t cts_nvm_ret_t
typedef struct cts_nvm_head_t cts_nvm_head_t
typedef struct cts_nvm_frame_t cts_nvm_frame_t
NVM frame structure, allows for convenient hardware implementation.
Enumerations
enum cts_nvm_ret_t {
CTS_NVM_ERR, CTS_NVM_OK, CTS_NVM_WRITE_FAILED, CTS_NVM_READ_FAILED,
CTS_NVM_CONFIG_INVALID, CTS_NVM_PAGE_INVALID, CTS_NVM_HW_INIT_FAILED, CTS_NVM_PAGE_EXPIRED
}
Functions
cts_nvm_ret_t CTS_NVM_Init ()
Perform NVM initialisation.
cts_nvm_ret_t CTS_NVM_Load (uint8_t *destBuff, uint32_t length)
Load CTS application configuration from NVM. Performs CRC check.
cts_nvm_ret_t CTS_NVM_Store (uint8_t *srcBuff, uint32_t length)
Store CTS application configuration to NVM. Performs CRC check.
cts_nvm_ret_t CTS_NVM_ForceStore (uint8_t *dataBuff, uint32_t dataLength)
Clear NVM storage, and writes a default header.
uint8_t CTS_NVM_GetCRC8 (uint8_t *data, uint8_t len)
Calculates the 8-Bit CRC for len bytes.
Detailed Description
CTS_NVM_drv Header.
This driver provides a default interface for storing and retreiving non-volatile configuration settings. It assumes the configuration structure is the only thing that is stored, thus no addressing is required apart from the base address definition.
Copyright
Copyright(C) 2013 PowerbyProxi Ltd and PowerbyProxi, Inc. All rights reserved
The content of this file contains intellectual property including copyright and confidential information owned by PowerbyProxi Ltd and PowerbyProxi, Inc. and is only to be used in accordance with the terms of the licence. The content of this file and/or its use may be covered by New Zealand, US and/or other foreign patents. The content of this file remains the property of PowerbyProxi Ltd and PowerbyProxi, Inc. Dissemination or reproduction of the content of this file or part hereof is strictly prohibited unless written permission is obtained from PowerbyProxi Ltd or PowerbyProxi, Inc.
Definition in file CTS_NVM_drv.h.
Macro Definition Documentation
#define CTS_NVM_BASE_ADDRESS (0x080E0000)
Definition at line 42 of file CTS_NVM_drv.h.
Referenced by CTS_NVM_ForceStore(), CTS_NVM_Load(), and CTS_NVM_Store().
#define CTS_NVM_DATA_BYTES (CTS_NVM_FRAME_BYTES - CTS_NVM_HEADER_BYTES)
Definition at line 46 of file CTS_NVM_drv.h.
#define CTS_NVM_FRAME_BYTES (512)
Definition at line 40 of file CTS_NVM_drv.h.
#define CTS_NVM_HEADER_BYTES (sizeof(cts_nvm_head_t))
Definition at line 45 of file CTS_NVM_drv.h.
#define CTS_NVM_MAX_CYCLES (0)
Definition at line 41 of file CTS_NVM_drv.h.
Referenced by CTS_NVM_Store().
Typedef Documentation
typedef struct cts_nvm_frame_t cts_nvm_frame_t
NVM frame structure, allows for convenient hardware implementation.
typedef struct cts_nvm_head_t cts_nvm_head_t
typedef enum cts_nvm_ret_t cts_nvm_ret_t
Enumeration Type Documentation
enum cts_nvm_ret_t
Enumerator
CTS_NVM_ERR
CTS_NVM_OK
CTS_NVM_WRITE_FAILED
CTS_NVM_READ_FAILED
CTS_NVM_CONFIG_INVALID
CTS_NVM_PAGE_INVALID
CTS_NVM_HW_INIT_FAILED
CTS_NVM_PAGE_EXPIRED
Definition at line 51 of file CTS_NVM_drv.h.
Function Documentation
cts_nvm_ret_t CTS_NVM_ForceStore (uint8_t * dataBuff, uint32_t dataLength)
Clear NVM storage, and writes a default header.
Clear NVM storage, and writes a default header.
Writes a CTS NVM page to the NVM without retreiving and checking existing data in the NBM. Makes sure the page is stored valid so that a next CTS_NVM_Store operation succeeds, given that the NVM doesnt cause any errors.
Parameters
dataBuff structure to store in default frame
dataLength size of the structure to store on a CTS_NVM_Store command, used for read validation.
Return values
CTS_NVM_WRITE_FAILED Something went wrong writing to NVM
CTS_NVM_PAGE_INVALID Default page readback failed.
CTS_NVM_OK Configuration was succesfully stored
Definition at line 183 of file CTS_NVM_drv.c.
References CTS_NVM_BASE_ADDRESS, CTS_NVM_GetCRC8(), CTS_NVM_OK, CTS_NVM_PAGE_INVALID, CTS_NVM_WRITE_FAILED, cts_nvm_frame_t::data, cts_nvm_head_t::dataCRC, cts_nvm_head_t::dataSize, DEBUG_LINE, cts_nvm_frame_t::head, cts_nvm_head_t::headCRC, HW_NVM_COMPARE, HW_NVM_OK, HW_NVM_WRITE_BLOCK, and cts_nvm_head_t::writeCount.
Referenced by main().
uint8_t CTS_NVM_GetCRC8 (uint8_t * data, uint8_t len)
Calculates the 8-Bit CRC for len bytes.
Parameters
data byte array to perform CRC calculation for/on
len the number of bytes to include in the calculation
Return values
8 bit CRC value calculated
Definition at line 332 of file CTS_NVM_drv.c.
Referenced by CTS_NVM_ForceStore(), and CTS_NVM_Store().
cts_nvm_ret_t CTS_NVM_Init ()
Perform NVM initialisation.
Return values
CTS_NVM_HW_INIT_FAILED Hardware initialisation failed
CTS_NVM_OK initialisation successfull
Definition at line 62 of file CTS_NVM_drv.c.
References CTS_NVM_HW_INIT_FAILED, CTS_NVM_OK, HW_NVM_INIT, and HW_NVM_OK.
Referenced by main().
cts_nvm_ret_t CTS_NVM_Load (uint8_t * destBuff, uint32_t length)
Load CTS application configuration from NVM. Performs CRC check.
Attempts to load the CTS application configuration from NVM. If this configuration is invalid, it will state so in the return value.
Parameters
destBuff buffer to store the retreived structure in
length size of the structure to read, used for validation
Return values
CTS_NVM_READ_FAILED Something went wrong reading from NVM
CTS_NVM_PAGE_INVALID Page retreived from NVM is invalid
CTS_NVM_OK Configuration was succesfully retreived
Definition at line 92 of file CTS_NVM_drv.c.
References CTS_NVM_BASE_ADDRESS, CTS_NVM_OK, CTS_NVM_PAGE_INVALID, CTS_NVM_READ_FAILED, cts_nvm_frame_t::data, HW_NVM_OK, and HW_NVM_READ_BLOCK.
Referenced by main().
cts_nvm_ret_t CTS_NVM_Store (uint8_t * srcBuff, uint32_t dataLength)
Store CTS application configuration to NVM. Performs CRC check.
Attempts to store the CTS application configuration from NVM. If this fails (checked by readback), it will state so in the return value.
Parameters
srcBuff buffer containing the structure to be stored
dataLength size of the structure to store, used for read validation
Return values
CTS_NVM_STORE_FAILED Something went wrong writing to NVM
CTS_NVM_PAGE_EXPIRED NVM frame has been written to many times
CTS_NVM_PAGE_INVALID Page retreived from NVM is invalid
CTS_NVM_OK Configuration was succesfully stored
Definition at line 236 of file CTS_NVM_drv.c.
References CTS_NVM_BASE_ADDRESS, CTS_NVM_GetCRC8(), CTS_NVM_MAX_CYCLES, CTS_NVM_OK, CTS_NVM_PAGE_EXPIRED, CTS_NVM_PAGE_INVALID, CTS_NVM_READ_FAILED, CTS_NVM_WRITE_FAILED, cts_nvm_frame_t::data, cts_nvm_head_t::dataCRC, cts_nvm_head_t::dataSize, cts_nvm_frame_t::head, cts_nvm_head_t::headCRC, HW_NVM_COMPARE, HW_NVM_OK, HW_NVM_READ_BLOCK, HW_NVM_WRITE_BLOCK, and cts_nvm_head_t::writeCount.
Referenced by main().