PBP Template: Main.c File Reference
Main.c File Reference
Application Entry Point.
#include "Global.h"
#include "RS232_drv.h"
#include "TERM_Lib.h"
#include "AppConfig.h"
#include <string.h>
#include "CTS_NVM_drv.h"
#include "stm32f4xx.h"
#include "misc.h"
#include "stm32f4xx_usart.h"
#include "stm32f4xx_rcc.h"
#include "stm32f4xx_gpio.h"
Functions
int main (void)
application entry point
void TERM_PutByte_Helper (uint8_t data)
Detailed Description
Application Entry Point.
The main function in this file serves as the application entry point. It is responsible for doing hardware/application initialisation in the correct order, and for servicing tasks needed for the application. All tasks are called from here, a new task can only run if the previous task has return a value.
Copyright
Copyright(C) 2013 PowerbyProxi Ltd and PowerbyProxi, Inc. All rights reserved
The content of this file contains intellectual property including copyright and confidential information owned by PowerbyProxi Ltd and PowerbyProxi, Inc. and is only to be used in accordance with the terms of the licence. The content of this file and/or its use may be covered by New Zealand, US and/or other foreign patents. The content of this file remains the property of PowerbyProxi Ltd and PowerbyProxi, Inc. Dissemination or reproduction of the content of this file or part hereof is strictly prohibited unless written permission is obtained from PowerbyProxi Ltd or PowerbyProxi, Inc.
Definition in file Main.c.
Function Documentation
int main (void)
application entry point
Return values
0 error, this function should not return!
Definition at line 60 of file Main.c.
References CTS_NVM_ForceStore(), CTS_NVM_Init(), CTS_NVM_Load(), CTS_NVM_OK, CTS_NVM_Store(), DEBUG_LINE, DEBUG_STRING, RS232_GetByteBlock(), RS232_GetRXPacketCount(), RS232_Init(), TERM_Lib_Init(), TERM_PutByte_Helper(), and app_config_t::testString.
void TERM_PutByte_Helper (uint8_t data)
Definition at line 146 of file Main.c.
References RS232_PutByte().
Referenced by main().