PBP Template: Drivers/RS232_Driver/RS232_drv.h File Reference
RS232_drv.h File Reference
Generic RS232 driver, interrupt/buffer based.
#include "Global.h"
#include "HardwareConfig.h"
Data Structures
struct rs232_ring_buff_t
struct rs232_config_t
Macros
#define RS232_RX_FIFO_BUFF_SIZE (UART_RX_BUFFER_LENGTH)
#define RS232_TX_FIFO_BUFF_SIZE (UART_TX_BUFFER_LENGTH)
#define RS232_RX_BUFF_MASK (RS232_RX_FIFO_BUFF_SIZE-1)
#define RS232_TX_BUFF_MASK (RS232_TX_FIFO_BUFF_SIZE-1)
Enumerations
enum rs232_err_t {
RS232_ERR, RS232_OK, RS232_INVALID_PARITY, RS232_INVALID_DATA_SIZE,
RS232_INVALID_STOPBITS, RS232_BUFFER_OVERRUN, RS232_BUFFER_FULL, RS232_NOT_ENOUGH_ELEMENTS,
RS232_NOT_ENOUGH_SPACE
}
Functions
rs232_err_t RS232_Init (void)
Configures and activates the UART peripheral.
rs232_err_t RS232_Config (uint32_t BaudRate, uint8_t DataBits, char Parity, uint8_t StopBits)
Configures the UART peripheral settings.
uint8_t RS232_GetByte (void)
Get a byte from the RS232 receive buffer.
rs232_err_t RS232_PutByte (uint8_t data)
Write a byte to the RS232 TX buffer.
rs232_err_t RS232_GetByteBlock (uint8_t *BlockBuffer, uint32_t Count)
Get a block of bytes form the RS232 RX buffer.
rs232_err_t RS232_PutByteBlock (uint8_t *DataBlock, uint32_t Count)
Write a block of bytes to the RS232 TX buffer.
rs232_err_t RS232_PutString (char *String)
Write a string to the RS232 TX buffer.
void RS232_ClearErrors ()
Clear RS232 peripheral error state, use sparingly.
uint32_t RS232_GetRXPacketCount ()
Get the number of waiting bytes in the RX buffer.
uint32_t RS232_GetTXPacketCount (void)
Get the number of waiting bytes in the TX buffer.
uint32_t RS232_GetTXBufferSize (void)
Get maximum size of the TX buffer.
uint32_t RS232_GetRXBufferSize (void)
Get maximum size of the RX buffer.
uint32_t RS232_GetTXBufferSpace (void)
Get the number of free slots in the TX buffer.
uint32_t RS232_GetRXBufferSpace (void)
Get the number of free slots in the TX buffer.
void _RS232_RXInterrupt (uint8_t TheData)
RX interrupt callback function.
void _RS232_TXInterrupt (void)
TX interrupt callback function.
Detailed Description
Generic RS232 driver, interrupt/buffer based.
Interrupt based RS232 implementation. This implementation uses a seperate RX and TX buffer, which are filles/emptied using interrupts. Relies on a lower level hardware implementation (hw_RS232_drv.h)
Copyright
Copyright(C) 2013 PowerbyProxi Ltd and PowerbyProxi, Inc. All rights reserved
The content of this file contains intellectual property including copyright and confidential information owned by PowerbyProxi Ltd and PowerbyProxi, Inc. and is only to be used in accordance with the terms of the licence. The content of this file and/or its use may be covered by New Zealand, US and/or other foreign patents. The content of this file remains the property of PowerbyProxi Ltd and PowerbyProxi, Inc. Dissemination or reproduction of the content of this file or part hereof is strictly prohibited unless written permission is obtained from PowerbyProxi Ltd or PowerbyProxi, Inc.
Definition in file RS232_drv.h.
Macro Definition Documentation
#define RS232_RX_BUFF_MASK (RS232_RX_FIFO_BUFF_SIZE-1)
Definition at line 42 of file RS232_drv.h.
Referenced by _RS232_RXInterrupt(), RS232_GetByte(), and RS232_GetByteBlock().
#define RS232_RX_FIFO_BUFF_SIZE (UART_RX_BUFFER_LENGTH)
Definition at line 39 of file RS232_drv.h.
Referenced by _RS232_RXInterrupt(), and RS232_Init().
#define RS232_TX_BUFF_MASK (RS232_TX_FIFO_BUFF_SIZE-1)
Definition at line 43 of file RS232_drv.h.
Referenced by _RS232_TXInterrupt(), RS232_PutByte(), and RS232_PutByteBlock().
#define RS232_TX_FIFO_BUFF_SIZE (UART_TX_BUFFER_LENGTH)
Definition at line 40 of file RS232_drv.h.
Referenced by RS232_Init().
Enumeration Type Documentation
enum rs232_err_t
Enumerator
RS232_ERR
RS232_OK
RS232_INVALID_PARITY
RS232_INVALID_DATA_SIZE
RS232_INVALID_STOPBITS
RS232_BUFFER_OVERRUN
RS232_BUFFER_FULL
RS232_NOT_ENOUGH_ELEMENTS
RS232_NOT_ENOUGH_SPACE
Definition at line 70 of file RS232_drv.h.
Function Documentation
void _RS232_RXInterrupt (uint8_t TheData)
RX interrupt callback function.
This function is called by a lower layer interrupt handler. It takes care of filling the RS232 RX buffer upon receiving a new byte. If the buffer is full, the data is discarded
Definition at line 491 of file RS232_drv.c.
References rs232_ring_buff_t::headPos, rs232_ring_buff_t::packetCount, rs232_ring_buff_t::pBuffer, RS232_RX_BUFF_MASK, and RS232_RX_FIFO_BUFF_SIZE.
Referenced by RS232_Init().
void _RS232_TXInterrupt (void)
TX interrupt callback function.
This function is called by a lower layer interrupt handler. It takes care of emtying the RS232 TX buffer when the peripheral is available. If the buffer is empty, the interrupt is disabled.
Definition at line 520 of file RS232_drv.c.
References HW_INT_DISABLED, HW_RS232_SEND_BYTE, HW_RS232_TX_INTERRUPT, HW_SET_INTERRUPT_STATE, rs232_ring_buff_t::packetCount, rs232_ring_buff_t::pBuffer, RS232_TX_BUFF_MASK, and rs232_ring_buff_t::tailPos.
Referenced by RS232_Init().
void RS232_ClearErrors ()
Clear RS232 peripheral error state, use sparingly.
Definition at line 392 of file RS232_drv.c.
References HW_RS232_CLEAR_ERRORS.
rs232_err_t RS232_Config (uint32_t BaudRate, uint8_t DataBits, char Parity, uint8_t StopBits)
Configures the UART peripheral settings.
Sets the baudrate, number of databits, type of parity and the number of stopbits.
Note
In case one of the inputs is invalid, the function returns with a corresponding error. Some, or all of the other settings might be set depending on which setting failed.
Parameters
BaudRate buad rate to be set in bits/s (2400,4800,9600.. up to 115200)
DataBits The number of bits per data packet (8 or 9)
Parity Parity type used. N=none, E=even, O=odd;
StopBits number of stopbits used (1 or 2)
Return values
RS232_INVALID_DATA_SIZE Datasize not supported
RS232_INVALID_PARITY Given parity type not supported
RS232_INVALID_STOPBITS Number of stopbits not supported
Definition at line 125 of file RS232_drv.c.
References HW_RS232_SET_BAUDRATE, HW_RS232_SET_DATABITS_8, HW_RS232_SET_DATABITS_9, HW_RS232_SET_PARITY_EVEN, HW_RS232_SET_PARITY_NONE, HW_RS232_SET_PARITY_ODD, HW_RS232_SET_STOPBITS_1, HW_RS232_SET_STOPBITS_2, RS232_INVALID_DATA_SIZE, RS232_INVALID_PARITY, RS232_INVALID_STOPBITS, and RS232_OK.
Referenced by RS232_Init().
uint8_t RS232_GetByte (void)
Get a byte from the RS232 receive buffer.
Return values
The data taken from the receive buffer
Definition at line 182 of file RS232_drv.c.
References HW_GET_RX_INTERRUPT_STATE, HW_INT_DISABLED, HW_RS232_RX_INTERRUPT, HW_SET_INTERRUPT_STATE, rs232_ring_buff_t::packetCount, rs232_ring_buff_t::pBuffer, RS232_RX_BUFF_MASK, and rs232_ring_buff_t::tailPos.
rs232_err_t RS232_GetByteBlock (uint8_t * BlockBuffer, uint32_t Count)
Get a block of bytes form the RS232 RX buffer.
Parameters
BlockBuffer the memory to which the read byte from the RX buffer should be written to. Should have at least Count bytes of space!
Count the number of bytes to get from the RX buffer
Return values
RS232_NOT_ENOUGH_ELEMENTS Less than Count bytes available, nothing is read
RS232_OK Succes, Count bytes were read from BlockBuffer
Definition at line 273 of file RS232_drv.c.
References HW_GET_RX_INTERRUPT_STATE, HW_INT_DISABLED, HW_RS232_RX_INTERRUPT, HW_SET_INTERRUPT_STATE, rs232_ring_buff_t::packetCount, rs232_ring_buff_t::pBuffer, RS232_NOT_ENOUGH_ELEMENTS, RS232_OK, RS232_RX_BUFF_MASK, and rs232_ring_buff_t::tailPos.
Referenced by main().
uint32_t RS232_GetRXBufferSize (void)
Get maximum size of the RX buffer.
Return values
Maximum size of the RX buffer
Definition at line 445 of file RS232_drv.c.
References rs232_ring_buff_t::size.
uint32_t RS232_GetRXBufferSpace (void)
Get the number of free slots in the TX buffer.
Return values
Number of free slots in the TX buffer
Definition at line 470 of file RS232_drv.c.
References HW_GET_RX_INTERRUPT_STATE, HW_INT_DISABLED, HW_RS232_RX_INTERRUPT, HW_SET_INTERRUPT_STATE, rs232_ring_buff_t::packetCount, and rs232_ring_buff_t::size.
uint32_t RS232_GetRXPacketCount ()
Get the number of waiting bytes in the RX buffer.
Return values
Number of bytes waiting in the RX buffer
Definition at line 401 of file RS232_drv.c.
References HW_GET_RX_INTERRUPT_STATE, HW_INT_DISABLED, HW_RS232_RX_INTERRUPT, HW_SET_INTERRUPT_STATE, and rs232_ring_buff_t::packetCount.
Referenced by main().
uint32_t RS232_GetTXBufferSize (void)
Get maximum size of the TX buffer.
Return values
Maximum size of the TX buffer
Definition at line 436 of file RS232_drv.c.
References rs232_ring_buff_t::size.
uint32_t RS232_GetTXBufferSpace (void)
Get the number of free slots in the TX buffer.
Return values
Number of free slots in the TX buffer
Definition at line 454 of file RS232_drv.c.
References HW_GET_TX_INTERRUPT_STATE, HW_INT_DISABLED, HW_RS232_TX_INTERRUPT, HW_SET_INTERRUPT_STATE, rs232_ring_buff_t::packetCount, and rs232_ring_buff_t::size.
uint32_t RS232_GetTXPacketCount (void)
Get the number of waiting bytes in the TX buffer.
Return values
Number of bytes waiting in the TX buffer
Definition at line 419 of file RS232_drv.c.
References HW_GET_TX_INTERRUPT_STATE, HW_INT_DISABLED, HW_RS232_TX_INTERRUPT, HW_SET_INTERRUPT_STATE, and rs232_ring_buff_t::packetCount.
rs232_err_t RS232_Init (void)
Configures and activates the UART peripheral.
Initialises the RX/TX buffers, UART Peripheral, and the RX/TX interrupts. After all is set, the hardware is enabled.
Return values
RS232_OK Init went ok, else, see rs232_err_t
Definition at line 66 of file RS232_drv.c.
References _RS232_RXInterrupt(), _RS232_TXInterrupt(), rs232_ring_buff_t::headPos, HW_RS232_ENABLE, HW_RS232_INIT, HW_RS232_SETUP_INTERRUPTS, rs232_ring_buff_t::packetCount, rs232_ring_buff_t::pBuffer, RS232_Config(), RS232_RX_Buffer_Mem, RS232_RX_FIFO_BUFF_SIZE, RS232_TX_Buffer_Mem, RS232_TX_FIFO_BUFF_SIZE, rs232_ring_buff_t::size, and rs232_ring_buff_t::tailPos.
Referenced by main().
rs232_err_t RS232_PutByte (uint8_t data)
Write a byte to the RS232 TX buffer.
Parameters
data data to write to the RS232 TX buffer
Return values
RS232_OK Byte was written to the buffer
RS232_BUFFER_FULL No more space was available in the buffer
Definition at line 224 of file RS232_drv.c.
References rs232_ring_buff_t::headPos, HW_GET_TX_INTERRUPT_STATE, HW_INT_DISABLED, HW_INT_ENABLED, HW_RS232_TX_INTERRUPT, HW_SET_INTERRUPT_STATE, rs232_ring_buff_t::packetCount, rs232_ring_buff_t::pBuffer, RS232_BUFFER_FULL, RS232_OK, RS232_TX_BUFF_MASK, and rs232_ring_buff_t::size.
Referenced by TERM_PutByte_Helper().
rs232_err_t RS232_PutByteBlock (uint8_t * DataBlock, uint32_t Count)
Write a block of bytes to the RS232 TX buffer.
Parameters
DataBlock the array of bytes to be added to the TX buffer. Should have at least Count elements!
Count the number of bytes to write to the TX buffer
Return values
RS232_NOT_ENOUGH_SPACE Less than Count bytes of space in TX buffer, nothing is written
RS232_OK Succes, Count bytes were written to the TX buffer.
Definition at line 322 of file RS232_drv.c.
References rs232_ring_buff_t::headPos, HW_GET_TX_INTERRUPT_STATE, HW_INT_DISABLED, HW_INT_ENABLED, HW_RS232_TX_INTERRUPT, HW_SET_INTERRUPT_STATE, rs232_ring_buff_t::packetCount, rs232_ring_buff_t::pBuffer, RS232_NOT_ENOUGH_SPACE, RS232_OK, RS232_TX_BUFF_MASK, and rs232_ring_buff_t::size.
Referenced by RS232_PutString().
rs232_err_t RS232_PutString (char * String)
Write a string to the RS232 TX buffer.
Parameters
String the array of characters (string) to be added to the TX buffer. The string should '0' terminate!
Return values
RS232_NOT_ENOUGH_SPACE Less bytes than string length in TX buffer, nothing is written
RS232_OK Succes, String was written to the TX buffer
Definition at line 367 of file RS232_drv.c.
References RS232_NOT_ENOUGH_SPACE, RS232_PutByteBlock(), and rs232_ring_buff_t::size.