PBP Template: Libs/TERM_Lib/TERM_Lib.c File Reference
TERM_Lib.c File Reference
TERM_Lib Source.
#include "Global.h"
#include "TERM_Lib.h"
Functions
void TERM_Lib_Init (void(*TERM_Write_Callback)(uint8_t data))
TERM_Lib initialiser.
void TERM_PutString (char *string)
Puts a string out on the TERM channel.
void TERM_PutLine (char *string)
Puts a string out on the TERM channel, including newline.
void TERM_PutHex (uint8_t *src, uint8_t nrBytes)
Converts a binary number into its hex representation, and sends it out.
void TERM_PutDecimal (int32_t val, uint8_t length)
Converts a binary number into its decimal representation, and sends it out.
Variables
void(* TERM_PutByte)(uint8_t data)
Detailed Description
TERM_Lib Source.
This library contains functions to allow for a simple terminal like communication with an embedded device. It can send character outputs over a arbritray channel, and provides a structure for command induced function calls
Copyright
Copyright(C) 2013 PowerbyProxi Ltd and PowerbyProxi, Inc. All rights reserved
The content of this file contains intellectual property including copyright and confidential information owned by PowerbyProxi Ltd and PowerbyProxi, Inc. and is only to be used in accordance with the terms of the licence. The content of this file and/or its use may be covered by New Zealand, US and/or other foreign patents. The content of this file remains the property of PowerbyProxi Ltd and PowerbyProxi, Inc. Dissemination or reproduction of the content of this file or part hereof is strictly prohibited unless written permission is obtained from PowerbyProxi Ltd or PowerbyProxi, Inc.
Definition in file TERM_Lib.c.
Function Documentation
void TERM_Lib_Init (void(*)(uint8_t data) TERM_Write_Callback)
TERM_Lib initialiser.
TERM_Lib initialiser. Call this function to prepare this module for use
Parameters
TERM_Write_Callback Callback function used to register a function that writes out a byte to the desired channel
Definition at line 62 of file TERM_Lib.c.
References TERM_PutByte.
Referenced by main().
void TERM_PutDecimal (int32_t val, uint8_t length)
Converts a binary number into its decimal representation, and sends it out.
Converts a binary number into a length number of digits decimal representation. If the source value had more decimal digits, only the bottom length digits are given. After conversion the number is put onto the TERM channel.
Parameters
val binary number to convert into a decimal output
length the number of decimals to show in the output
Definition at line 158 of file TERM_Lib.c.
References TERM_PutString().
void TERM_PutHex (uint8_t * src, uint8_t nrBytes)
Converts a binary number into its hex representation, and sends it out.
Treats a number as an array of unsigned bytes, of which nrBytes LSBs are converted to HEX format, starting with the MSB of the LSBs. This is then sent out on the TERM channel
Parameters
src pointer to the first byte to convert
nrBytes number of bytes to convert
Example Usage:
uint16_t value = 0x1234;
TERM_PutHex((uint8_t *)&value, sizeof(value)); //this gives 0x1234
TERM_PutHex((uint8_t *)&value, 1); //this gives 0x34
TERM_PutHex((uint8_t *)&value, 3); //this gives 0x??1234
Definition at line 131 of file TERM_Lib.c.
References TERM_PutByte.
void TERM_PutLine (char * string)
Puts a string out on the TERM channel, including newline.
Parameters
string The string to send. Must be 0 terminated!
Definition at line 90 of file TERM_Lib.c.
References TERM_PutString().
void TERM_PutString (char * string)
Puts a string out on the TERM channel.
Parameters
string The string to send. Must be 0 terminated!
Definition at line 73 of file TERM_Lib.c.
References TERM_MAX_STRING_LENGTH, and TERM_PutByte.
Referenced by TERM_PutDecimal(), and TERM_PutLine().
Variable Documentation
void(* TERM_PutByte)(uint8_t data)
Definition at line 39 of file TERM_Lib.c.
Referenced by TERM_Lib_Init(), TERM_PutHex(), and TERM_PutString().