PBP Template: Drivers/RS232_Driver/Hardware/hw_RS232_drv.c File Reference
hw_RS232_drv.c File Reference
STM32 RS232 driver hardware layer.
#include "Global.h"
#include "hw_RS232_drv.h"
#include "stm32f4xx.h"
#include "misc.h"
#include "stm32f4xx_usart.h"
#include "stm32f4xx_rcc.h"
#include "stm32f4xx_gpio.h"
Functions
void hw_RS232_Init (void)
Configures and activates the UART peripheral hardware.
void hw_RS232_Set_Baudrate (uint32_t BaudRate)
Calculates and sets the USART baud rate settings.
void hw_RS232_Setup_Interrupts (void(*RX_Interrupt_Handler)(uint8_t), void(*TX_Interrupt_Handler)(void))
Set up the STM32 interrupt controller and USART interrupts.
void USART6_IRQHandler (void)
STM32 USART interrupt. Calls IRQ callbacks and resets flag.
Variables
volatile USART_TypeDef * p_Usart_Port = USART_PORT_DEF
pointer to STM32 USART peripheral to be used
void(* hw_RX_Interrupt_Callback)(uint8_t)
pointer to higher level RX interrupt handler callback function
void(* hw_TX_Interrupt_Callback)()
pointer to higher level TX interrupt handler callback function
Detailed Description
STM32 RS232 driver hardware layer.
Hardware level calls required by the RS232 Generic driver RS232_drv.c This layer is mostly macro based although some more complex functions have an implementation here.
Copyright
Copyright(C) 2013 PowerbyProxi Ltd and PowerbyProxi, Inc. All rights reserved
The content of this file contains intellectual property including copyright and confidential information owned by PowerbyProxi Ltd and PowerbyProxi, Inc. and is only to be used in accordance with the terms of the licence. The content of this file and/or its use may be covered by New Zealand, US and/or other foreign patents. The content of this file remains the property of PowerbyProxi Ltd and PowerbyProxi, Inc. Dissemination or reproduction of the content of this file or part hereof is strictly prohibited unless written permission is obtained from PowerbyProxi Ltd or PowerbyProxi, Inc.
Definition in file hw_RS232_drv.c.
Function Documentation
void hw_RS232_Init (void)
Configures and activates the UART peripheral hardware.
Setup GPIO clock, direction, function for use with USART. Also set USART peripheral to default settings (9600,8,N,1).
Definition at line 64 of file hw_RS232_drv.c.
void hw_RS232_Set_Baudrate (uint32_t BaudRate)
Calculates and sets the USART baud rate settings.
Parameters
BaudRate baud rate to be set (2400,4800,9600... up to 115200)
Definition at line 107 of file hw_RS232_drv.c.
References p_Usart_Port.
void hw_RS232_Setup_Interrupts (void(*)(uint8_t) RX_Interrupt_Handler, void(*)(void) TX_Interrupt_Handler)
Set up the STM32 interrupt controller and USART interrupts.
This functions stores the higher level interrupt callback function pointers. Next the RX empty en TX empty interrupt are enabled which call the callback functions.
Parameters
RX_Interrupt_Handler pointer to higher level RX IRQ callback
TX_Interrupt_Handler pointer to higher level TX IRQ callback
Definition at line 168 of file hw_RS232_drv.c.
References hw_RX_Interrupt_Callback, and hw_TX_Interrupt_Callback.
void USART6_IRQHandler (void)
STM32 USART interrupt. Calls IRQ callbacks and resets flag.
Definition at line 200 of file hw_RS232_drv.c.
References hw_RX_Interrupt_Callback, hw_TX_Interrupt_Callback, and p_Usart_Port.
Variable Documentation
void(* hw_RX_Interrupt_Callback)(uint8_t)
pointer to higher level RX interrupt handler callback function
Definition at line 47 of file hw_RS232_drv.c.
Referenced by hw_RS232_Setup_Interrupts(), and USART6_IRQHandler().
void(* hw_TX_Interrupt_Callback)()
pointer to higher level TX interrupt handler callback function
Definition at line 49 of file hw_RS232_drv.c.
Referenced by hw_RS232_Setup_Interrupts(), and USART6_IRQHandler().
volatile USART_TypeDef* p_Usart_Port = USART_PORT_DEF
pointer to STM32 USART peripheral to be used
Definition at line 44 of file hw_RS232_drv.c.
Referenced by hw_RS232_Set_Baudrate(), and USART6_IRQHandler().